name: Create release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  run-unit-tests:
    uses: ./.github/workflows/reusable_run_unit_tests.yml

  generate-compose-compiler-metrics:
    needs: run-unit-tests
    uses: ./.github/workflows/reusable_generate_compose_compiler_metrics.yml
    secrets: inherit

  build-release-artifacts:
    needs: generate-compose-compiler-metrics
    uses: ./.github/workflows/reusable_build_release_artifacts.yml
    secrets: inherit
