name: Create release

on:
  push:
    tags:
      - '[1-9]+.[0-9]+.[0-9]+'

jobs:
  run-unit-tests:
    uses: ./.github/workflows/run_unit_tests.yml

  build-release-artifacts:
    needs: run-unit-tests
    uses: ./.github/workflows/build_release_artifacts.yml
