name: Generate Compose compiler metrics

on:
  workflow_call:

env:
  KEYSTORE_STORE_FILE: ${{ secrets.KEYSTORE_STORE_FILE }}
  KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
  KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
  KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}

jobs:
  generate-compose-compiler-metrics:
    name: Generate Compose compiler metrics
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Retrieve Android keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" > podcasts-compose-keystore.jks.asc
          gpg -d --passphrase "${{ secrets.KEYSTORE_BASE64_PASSPHRASE }}" --batch podcasts-compose-keystore.jks.asc > app/keystore.jks

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew commands executable
        run: chmod +x ./gradlew

      - name: Generate Compose compiler metrics
        run: ./gradlew assembleRelease -P.enableComposeCompilerReports=true --rerun-tasks

      - name: Upload Compose compiler metrics
        uses: actions/upload-artifact@v3
        with:
          name: compose-compiler-metrics
          path: app/build/compose_metrics/
