name: Build release artifacts and create release

on:
  workflow_call:

env:
  KEYSTORE_STORE_FILE: ${{ secrets.KEYSTORE_STORE_FILE }}
  KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
  KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
  KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}

  PODCAST_INDEX_API_KEY: ${{ secrets.PODCAST_INDEX_API_KEY }}
  PODCAST_INDEX_API_SECRET_KEY: ${{ secrets.PODCAST_INDEX_API_SECRET_KEY }}

jobs:
  build-release-artifacts-and-create-release:
    name: Build release artifacts and create release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Retrieve Android keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" > podcasts-compose-keystore.jks.asc
          gpg -d --passphrase "${{ secrets.KEYSTORE_BASE64_PASSPHRASE }}" --batch podcasts-compose-keystore.jks.asc > app/keystore.jks

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew commands executable
        run: chmod +x ./gradlew

      - name: Build release artifacts
        run: |
          ./gradlew assembleRelease
          ./gradlew bundleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          path: app/build/outputs/apk/release/podcasts*.apk

      - name: Upload Bundle
        uses: actions/upload-artifact@v3
        with:
          path: app/build/outputs/bundle/release/podcasts*.aab

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app/build/outputs/apk/release/podcasts*.apk
            app/build/outputs/bundle/release/podcasts*.aab
