name: PR_unit_tests

on:
  pull_request:
    branches:
      - 'development'

jobs:
  Unit-test:
    name: Run unit tests on PR in development
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distibution: 'temurin'
          java-version: '8'

      - name: Run unit tests
        run: ./gradlew test
